// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRdza2DiMAqqvwzq2LayrZr_ld2m3kEOk',
    appId: '1:779433925045:web:b751f67036453c240661fc',
    messagingSenderId: '779433925045',
    projectId: 'tukuntech-2026',
    authDomain: 'tukuntech-2026.firebaseapp.com',
    storageBucket: 'tukuntech-2026.firebasestorage.app',
    measurementId: 'G-05XEZ3STY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJGva_qjFoh8ko8JlIPHwgFxZfX9gSvLQ',
    appId: '1:779433925045:android:6337bb0518d9866b0661fc',
    messagingSenderId: '779433925045',
    projectId: 'tukuntech-2026',
    storageBucket: 'tukuntech-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfj74lCcEQiTawTGMLPJmgZP6JGiPCpLo',
    appId: '1:779433925045:ios:a674426547531a200661fc',
    messagingSenderId: '779433925045',
    projectId: 'tukuntech-2026',
    storageBucket: 'tukuntech-2026.firebasestorage.app',
    iosBundleId: 'com.example.tukuntech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfj74lCcEQiTawTGMLPJmgZP6JGiPCpLo',
    appId: '1:779433925045:ios:a674426547531a200661fc',
    messagingSenderId: '779433925045',
    projectId: 'tukuntech-2026',
    storageBucket: 'tukuntech-2026.firebasestorage.app',
    iosBundleId: 'com.example.tukuntech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRdza2DiMAqqvwzq2LayrZr_ld2m3kEOk',
    appId: '1:779433925045:web:e5ea64cf1f86f37b0661fc',
    messagingSenderId: '779433925045',
    projectId: 'tukuntech-2026',
    authDomain: 'tukuntech-2026.firebaseapp.com',
    storageBucket: 'tukuntech-2026.firebasestorage.app',
    measurementId: 'G-M33ZEBCG80',
  );
}
